### ISSUE TITLE
VMtFileExample

### ISSUE THREAD

**Issue by Yuri6037** [StoneLineDevTeam/UMod#19]
This the base example for the VMT converter.
[Oak.txt](https://github.com/StoneLineDevTeam/UMod/files/437061/Oak.txt)

**Comment by amau2001** [comment]
https://mega.nz/#!J05AmBjJ

**Comment by Yuri6037** [comment]
Thank you very much
I'll try to convert that as fast as I can...

**Comment by Yuri6037** [comment]
Closing issue as it's done...
