### ISSUE TITLE
Asset injecting, illegal...

### ISSUE THREAD

**Issue by Yuri6037** [StoneLineDevTeam/UMod#5]
This message is intended for anyone that is interested into UMod development. I need to tell you, and I know how much unfortunate this is, but what I'm trying to achive with dynamic asset loading is illegal in the design of Epic Games EULA, by the simple fact what I want to do is called editing AssetRegistry.bin at runtime and forcing the engine to reload it. Changing this file is illegal when done at runtime : this file is intended to be generated by UE4 Editor Asset Cooking process. Importing this asset cooking process into a runtime module would be illegal, and so under those problems I can't continue the game like that, however some last options remains legal in the EULA.

Indeed if direct asset registry modification during runtime is illegal, there's still a way as to proceduraly generate meshes and textures using custom decoders and custom file formats.
I think you'll understand that making custom formats and custom decoders is highly more complicated, and honnestly I need to tell you that I don't think I can do it.

I leave up to you C++ coders, better than me, if you can make a working implemention of FBX decoder inside UE4. Even if I can make FBX deconding myself, procedural mesh generation is unfortunatly impossible in UE4. Only procedural texture generation is possible.
I'm sorry but I have not the knowledge to make it possible to proceduraly generate meshes with materials and UVs on UE4 C++.

**Comment by Yuri6037** [comment]
Well, after a long speak on UE4 IRC, I might have find a solution to the issue.

**Comment by DatCaptainHorse** [comment]
What is the solution?

**Comment by Yuri6037** [comment]
Wow ! Someone is still interested ! So well the solution is easy : content packs. That means all addons that have media content to inject will put a Content.pak file with their lua folder inside the add-on folder.
GameModes will also have the same principe. And with that I will enable something that has been requested on gmod but not implemented due to engine limits : content pack injection dynamically in game ! (Note that while you will lua mount your pak you will "crash" the client as injection is done on the normal thread. Second note : models added before content pack mount will probably need reload... Third note : maps will unfortunately not be able to be dynamically injected while in game as the client must spawn somewhere and it wouldn't be playable if the map was missing).

**Comment by Yuri6037** [comment]
Ok so now Asset Injection should be done but I can't test it right now... I need to figure out how to compile pak files to test it.

**Comment by Yuri6037** [comment]
By the way it should work, I'll close that issue. When I'll be able to test the system, I'll open a new one if it does not work as intended.
